// Get all divs with the class name 'contentArea' and store in a NodeList called 'buttons'
var buttons = document.getElementsByClassName('contentArea');

// Loop through NodeList and call the click() function on each button
for(var i = 0; i <= buttons.length; i++)  
   buttons[i].click();

//refresh the page when button is clicked, to load a new board
function refreshPage () 
{
    window.location.reload ();
};

//Add and take away a bingo marker
function markOff() 
{   
    
    $(".circular-square").click(function () {
        $(this).toggleClass("show");
    }); 
    /*for some reason this requires a click in between clicks 
    to work, adjust in future  ie toggle - blank - toggle */
};


//Creates a random image in each bingo cell
function randomImage(spaceID)
{   
    var imageArray = [  
        {src: "Images/ACNH_VillagerIcons/Admiral.png"},   
        {src: "Images/ACNH_VillagerIcons/Agent_S.png"},
        {src: "Images/ACNH_VillagerIcons/Agnes.png"},
        {src: "Images/ACNH_VillagerIcons/Chai.png"},
        {src: "Images/ACNH_VillagerIcons/Chelsea.png"},
        {src: "Images/ACNH_VillagerIcons/Etoile.png"},
        {src: "Images/ACNH_VillagerIcons/Marty.png"},
        {src: "Images/ACNH_VillagerIcons/Rilla.png"},
        {src: "Images/ACNH_VillagerIcons/Toby.png"},
        {src: "Images/ACNH_VillagerIcons/Al.png"},
        {src: "Images/ACNH_VillagerIcons/Alfonso.png"},
        {src: "Images/ACNH_VillagerIcons/Alice.png"},
        {src: "Images/ACNH_VillagerIcons/Alli.png"},
        {src: "Images/ACNH_VillagerIcons/Amelia.png"},
        {src: "Images/ACNH_VillagerIcons/Anabelle.png"},
        {src: "Images/ACNH_VillagerIcons/Anchovy.png"},
        {src: "Images/ACNH_VillagerIcons/Angus.png"},
        {src: "Images/ACNH_VillagerIcons/Anicotti.png"},
        {src: "Images/ACNH_VillagerIcons/Ankha.png"},
        {src: "Images/ACNH_VillagerIcons/Annalisa.png"},
        {src: "Images/ACNH_VillagerIcons/Annalise.png"},
        {src: "Images/ACNH_VillagerIcons/Antonio.png"},
        {src: "Images/ACNH_VillagerIcons/Apollo.png"},
        {src: "Images/ACNH_VillagerIcons/Apple.png"},
        {src: "Images/ACNH_VillagerIcons/Astrid.png"},
        {src: "Images/ACNH_VillagerIcons/Audie.png"},
        {src: "Images/ACNH_VillagerIcons/Aurora.png"},
        {src: "Images/ACNH_VillagerIcons/Ava.png"},
        {src: "Images/ACNH_VillagerIcons/Avery.png"},
        {src: "Images/ACNH_VillagerIcons/Axel.png"},
        {src: "Images/ACNH_VillagerIcons/Baabara.png"},
        {src: "Images/ACNH_VillagerIcons/Bam.png"},
        {src: "Images/ACNH_VillagerIcons/Bangle.png"},
        {src: "Images/ACNH_VillagerIcons/Barold.png"},
        {src: "Images/ACNH_VillagerIcons/Bea.png"},
        {src: "Images/ACNH_VillagerIcons/Beardo.png"},
        {src: "Images/ACNH_VillagerIcons/Beau.png"},
        {src: "Images/ACNH_VillagerIcons/Becky.png"},
        {src: "Images/ACNH_VillagerIcons/Bella.png"},
        {src: "Images/ACNH_VillagerIcons/Benedict.png"},
        {src: "Images/ACNH_VillagerIcons/Benjamin.png"},
        {src: "Images/ACNH_VillagerIcons/Bertha.png"},
        {src: "Images/ACNH_VillagerIcons/Bettina.png"},
        {src: "Images/ACNH_VillagerIcons/Bianca.png"},
        {src: "Images/ACNH_VillagerIcons/Biff.png"},
        {src: "Images/ACNH_VillagerIcons/Big_Top.png"},
        {src: "Images/ACNH_VillagerIcons/Bill.png"},
        {src: "Images/ACNH_VillagerIcons/Billy.png"},
        {src: "Images/ACNH_VillagerIcons/Biskit.png"},
        {src: "Images/ACNH_VillagerIcons/Bitty.png"},
        {src: "Images/ACNH_VillagerIcons/Blaire.png"},
        {src: "Images/ACNH_VillagerIcons/Blanche.png"},
        {src: "Images/ACNH_VillagerIcons/Bluebear.png"},
        {src: "Images/ACNH_VillagerIcons/Bob.png"},
        {src: "Images/ACNH_VillagerIcons/Bonbon.png"},
        {src: "Images/ACNH_VillagerIcons/Bones.png"},
        {src: "Images/ACNH_VillagerIcons/Boomer.png"},
        {src: "Images/ACNH_VillagerIcons/Boone.png"},
        {src: "Images/ACNH_VillagerIcons/Boots.png"},
        {src: "Images/ACNH_VillagerIcons/Boris.png"},
        {src: "Images/ACNH_VillagerIcons/Boyd.png"},
        {src: "Images/ACNH_VillagerIcons/Bree.png"},
        {src: "Images/ACNH_VillagerIcons/Broccolo.png"},
        {src: "Images/ACNH_VillagerIcons/Broffina.png"},
        {src: "Images/ACNH_VillagerIcons/Bruce.png"},
        {src: "Images/ACNH_VillagerIcons/Bubbles.png"},
        {src: "Images/ACNH_VillagerIcons/Buck.png"},
        {src: "Images/ACNH_VillagerIcons/Bud.png"},
        {src: "Images/ACNH_VillagerIcons/Bunnie.png"},
        {src: "Images/ACNH_VillagerIcons/Butch.png"},
        {src: "Images/ACNH_VillagerIcons/Buzz.png"},
        {src: "Images/ACNH_VillagerIcons/Cally.png"},
        {src: "Images/ACNH_VillagerIcons/Camofrog.png"},
        {src: "Images/ACNH_VillagerIcons/Canberra.png"},
        {src: "Images/ACNH_VillagerIcons/Candi.png"},
        {src: "Images/ACNH_VillagerIcons/Carmen.png"},
        {src: "Images/ACNH_VillagerIcons/Caroline.png"},
        {src: "Images/ACNH_VillagerIcons/Carrie.png"},
        {src: "Images/ACNH_VillagerIcons/Cashmere.png"},
        {src: "Images/ACNH_VillagerIcons/Celia.png"},
        {src: "Images/ACNH_VillagerIcons/Cesar.png"},
        {src: "Images/ACNH_VillagerIcons/Chadder.png"},
        {src: "Images/ACNH_VillagerIcons/Charlise.png"},
        {src: "Images/ACNH_VillagerIcons/Cheri.png"},
        {src: "Images/ACNH_VillagerIcons/Cherry.png"},
        {src: "Images/ACNH_VillagerIcons/Chester.png"},
        {src: "Images/ACNH_VillagerIcons/Chevre.png"},
        {src: "Images/ACNH_VillagerIcons/Chief.png"},
        {src: "Images/ACNH_VillagerIcons/Chops.png"},
        {src: "Images/ACNH_VillagerIcons/Chow.png"},
        {src: "Images/ACNH_VillagerIcons/Chrissy.png"},
        {src: "Images/ACNH_VillagerIcons/Claude.png"},
        {src: "Images/ACNH_VillagerIcons/Claudia.png"},
        {src: "Images/ACNH_VillagerIcons/Clay.png"},
        {src: "Images/ACNH_VillagerIcons/Cleo.png"},
        {src: "Images/ACNH_VillagerIcons/Clyde.png"},
        {src: "Images/ACNH_VillagerIcons/Coach.png"},
        {src: "Images/ACNH_VillagerIcons/Cobb.png"},
        {src: "Images/ACNH_VillagerIcons/Coco.png"},
        {src: "Images/ACNH_VillagerIcons/Cole.png"},
        {src: "Images/ACNH_VillagerIcons/Colton.png"},
        {src: "Images/ACNH_VillagerIcons/Cookie.png"},
        {src: "Images/ACNH_VillagerIcons/Cousteau.png"},
        {src: "Images/ACNH_VillagerIcons/Cranston.png"},
        {src: "Images/ACNH_VillagerIcons/Croque.png"},
        {src: "Images/ACNH_VillagerIcons/Cube.png"},
        {src: "Images/ACNH_VillagerIcons/Curlos.png"},
        {src: "Images/ACNH_VillagerIcons/Curly.png"},
        {src: "Images/ACNH_VillagerIcons/Curt.png"},
        {src: "Images/ACNH_VillagerIcons/Cyd.png"},
        {src: "Images/ACNH_VillagerIcons/Cyrano.png"},
        {src: "Images/ACNH_VillagerIcons/Daisy.png"},
        {src: "Images/ACNH_VillagerIcons/Deena.png"},
        {src: "Images/ACNH_VillagerIcons/Deirdre.png"},
        {src: "Images/ACNH_VillagerIcons/Del.png"},
        {src: "Images/ACNH_VillagerIcons/Deli.png"},
        {src: "Images/ACNH_VillagerIcons/Derwin.png"},
        {src: "Images/ACNH_VillagerIcons/Diana.png"},
        {src: "Images/ACNH_VillagerIcons/Diva.png"},
        {src: "Images/ACNH_VillagerIcons/Dizzy.png"},
        {src: "Images/ACNH_VillagerIcons/Dobie.png"},
        {src: "Images/ACNH_VillagerIcons/Doc.png"},
        {src: "Images/ACNH_VillagerIcons/Dom.png"},
        {src: "Images/ACNH_VillagerIcons/Dora.png"},
        {src: "Images/ACNH_VillagerIcons/Dotty.png"},
        {src: "Images/ACNH_VillagerIcons/Drago.png"},
        {src: "Images/ACNH_VillagerIcons/Drake.png"},
        {src: "Images/ACNH_VillagerIcons/Drift.png"},
        {src: "Images/ACNH_VillagerIcons/Ed.png"},
        {src: "Images/ACNH_VillagerIcons/Egbert.png"},
        {src: "Images/ACNH_VillagerIcons/Elise.png"},
        {src: "Images/ACNH_VillagerIcons/Ellie.png"},
        {src: "Images/ACNH_VillagerIcons/Elmer.png"},
        {src: "Images/ACNH_VillagerIcons/Eloise.png"},
        {src: "Images/ACNH_VillagerIcons/Elvis.png"},
        {src: "Images/ACNH_VillagerIcons/Erik.png"},
        {src: "Images/ACNH_VillagerIcons/Eugene.png"},
        {src: "Images/ACNH_VillagerIcons/Eunice.png"},
        {src: "Images/ACNH_VillagerIcons/Fang.png"},
        {src: "Images/ACNH_VillagerIcons/Fauna.png"},
        {src: "Images/ACNH_VillagerIcons/Felicity.png"},
        {src: "Images/ACNH_VillagerIcons/Filbert.png"},
        {src: "Images/ACNH_VillagerIcons/Flip.png"},
        {src: "Images/ACNH_VillagerIcons/Flo.png"},
        {src: "Images/ACNH_VillagerIcons/Flora.png"},
        {src: "Images/ACNH_VillagerIcons/Flurry.png"},
        {src: "Images/ACNH_VillagerIcons/Francine.png"},
        {src: "Images/ACNH_VillagerIcons/Frank.png"},
        {src: "Images/ACNH_VillagerIcons/Freckles.png"},
        {src: "Images/ACNH_VillagerIcons/Freya.png"},
        {src: "Images/ACNH_VillagerIcons/Friga.png"},
        {src: "Images/ACNH_VillagerIcons/Frita.png"},
        {src: "Images/ACNH_VillagerIcons/Frobert.png"},
        {src: "Images/ACNH_VillagerIcons/Fuchsia.png"},
        {src: "Images/ACNH_VillagerIcons/Gabi.png"},
        {src: "Images/ACNH_VillagerIcons/Gala.png"},
        {src: "Images/ACNH_VillagerIcons/Gaston.png"},
        {src: "Images/ACNH_VillagerIcons/Gayle.png"},
        {src: "Images/ACNH_VillagerIcons/Genji.png"},
        {src: "Images/ACNH_VillagerIcons/Gigi.png"},
        {src: "Images/ACNH_VillagerIcons/Gladys.png"},
        {src: "Images/ACNH_VillagerIcons/Gloria.png"},
        {src: "Images/ACNH_VillagerIcons/Goldie.png"},
        {src: "Images/ACNH_VillagerIcons/Gonzo.png"},
        {src: "Images/ACNH_VillagerIcons/Goose.png"},
        {src: "Images/ACNH_VillagerIcons/Graham.png"},
        {src: "Images/ACNH_VillagerIcons/Greta.png"},
        {src: "Images/ACNH_VillagerIcons/Grizzly.png"},
        {src: "Images/ACNH_VillagerIcons/Groucho.png"},
        {src: "Images/ACNH_VillagerIcons/Gruff.png"},
        {src: "Images/ACNH_VillagerIcons/Gwen.png"},
        {src: "Images/ACNH_VillagerIcons/Hamlet.png"},
        {src: "Images/ACNH_VillagerIcons/Hamphrey.png"},
        {src: "Images/ACNH_VillagerIcons/Hans.png"},
        {src: "Images/ACNH_VillagerIcons/Harry.png"},
        {src: "Images/ACNH_VillagerIcons/Hazel.png"},
        {src: "Images/ACNH_VillagerIcons/Henry.png"},
        {src: "Images/ACNH_VillagerIcons/Hippeux.png"},
        {src: "Images/ACNH_VillagerIcons/Hopkins.png"},
        {src: "Images/ACNH_VillagerIcons/Hopper.png"},
        {src: "Images/ACNH_VillagerIcons/Hornsby.png"},
        {src: "Images/ACNH_VillagerIcons/Huck.png"},
        {src: "Images/ACNH_VillagerIcons/Hugh.png"},
        {src: "Images/ACNH_VillagerIcons/Iggly.png"},
        {src: "Images/ACNH_VillagerIcons/Ike.png"},
        {src: "Images/ACNH_VillagerIcons/Jacob.png"},
        {src: "Images/ACNH_VillagerIcons/Jacques.png"},
        {src: "Images/ACNH_VillagerIcons/Jambette.png"},
        {src: "Images/ACNH_VillagerIcons/Jay.png"},
        {src: "Images/ACNH_VillagerIcons/Jeremiah.png"},
        {src: "Images/ACNH_VillagerIcons/Jitters.png"},
        {src: "Images/ACNH_VillagerIcons/Joey.png"},
        {src: "Images/ACNH_VillagerIcons/Judy.png"},
        {src: "Images/ACNH_VillagerIcons/Julia.png"},
        {src: "Images/ACNH_VillagerIcons/Julian.png"},
        {src: "Images/ACNH_VillagerIcons/June.png"},
        {src: "Images/ACNH_VillagerIcons/Kabuki.png"},
        {src: "Images/ACNH_VillagerIcons/Katt.png"},
        {src: "Images/ACNH_VillagerIcons/Keaton.png"},
        {src: "Images/ACNH_VillagerIcons/Ken.png"},
        {src: "Images/ACNH_VillagerIcons/Ketchup.png"},
        {src: "Images/ACNH_VillagerIcons/Kevin.png"},
        {src: "Images/ACNH_VillagerIcons/Kid_Cat.png"},
        {src: "Images/ACNH_VillagerIcons/Kidd.png"},
        {src: "Images/ACNH_VillagerIcons/Kiki.png"},
        {src: "Images/ACNH_VillagerIcons/Kitt.png"},
        {src: "Images/ACNH_VillagerIcons/Kitty.png"},
        {src: "Images/ACNH_VillagerIcons/Klaus.png"},
        {src: "Images/ACNH_VillagerIcons/Knox.png"},
        {src: "Images/ACNH_VillagerIcons/Kody.png"},
        {src: "Images/ACNH_VillagerIcons/Kyle.png"},
        {src: "Images/ACNH_VillagerIcons/Leonardo.png"},
        {src: "Images/ACNH_VillagerIcons/Leopold.png"},
        {src: "Images/ACNH_VillagerIcons/Lily.png"},
        {src: "Images/ACNH_VillagerIcons/Limberg.png"},
        {src: "Images/ACNH_VillagerIcons/Lionel.png"},
        {src: "Images/ACNH_VillagerIcons/Lobo.png"},
        {src: "Images/ACNH_VillagerIcons/Lolly.png"},
        {src: "Images/ACNH_VillagerIcons/Lopez.png"},
        {src: "Images/ACNH_VillagerIcons/Louie.png"},
        {src: "Images/ACNH_VillagerIcons/Lucha.png"},
        {src: "Images/ACNH_VillagerIcons/Lucky.png"},
        {src: "Images/ACNH_VillagerIcons/Lucy.png"},
        {src: "Images/ACNH_VillagerIcons/Lyman.png"},
        {src: "Images/ACNH_VillagerIcons/Mac.png"},
        {src: "Images/ACNH_VillagerIcons/Maddie.png"},
        {src: "Images/ACNH_VillagerIcons/Maelle.png"},
        {src: "Images/ACNH_VillagerIcons/Maggie.png"},
        {src: "Images/ACNH_VillagerIcons/Mallary.png"},
        {src: "Images/ACNH_VillagerIcons/Maple.png"},
        {src: "Images/ACNH_VillagerIcons/Marcel.png"},
        {src: "Images/ACNH_VillagerIcons/Marcie.png"},
        {src: "Images/ACNH_VillagerIcons/Margie.png"},
        {src: "Images/ACNH_VillagerIcons/Marina.png"},
        {src: "Images/ACNH_VillagerIcons/Marshal.png"},
        {src: "Images/ACNH_VillagerIcons/Mathilda.png"},
        {src: "Images/ACNH_VillagerIcons/Megan.png"},
        {src: "Images/ACNH_VillagerIcons/Melba.png"},
        {src: "Images/ACNH_VillagerIcons/Merengue.png"},
        {src: "Images/ACNH_VillagerIcons/Merry.png"},
        {src: "Images/ACNH_VillagerIcons/Midge.png"},
        {src: "Images/ACNH_VillagerIcons/Mint.png"},
        {src: "Images/ACNH_VillagerIcons/Mira.png"},
        {src: "Images/ACNH_VillagerIcons/Miranda.png"},
        {src: "Images/ACNH_VillagerIcons/Mitzi.png"},
        {src: "Images/ACNH_VillagerIcons/Moe.png"},
        {src: "Images/ACNH_VillagerIcons/Molly.png"},
        {src: "Images/ACNH_VillagerIcons/Monique.png"},
        {src: "Images/ACNH_VillagerIcons/Monty.png"},
        {src: "Images/ACNH_VillagerIcons/Moose.png"},
        {src: "Images/ACNH_VillagerIcons/Mott.png"},
        {src: "Images/ACNH_VillagerIcons/Muffy.png"},
        {src: "Images/ACNH_VillagerIcons/Murphy.png"},
        {src: "Images/ACNH_VillagerIcons/Nan.png"},
        {src: "Images/ACNH_VillagerIcons/Nana.png"},
        {src: "Images/ACNH_VillagerIcons/Naomi.png"},
        {src: "Images/ACNH_VillagerIcons/Nate.png"},
        {src: "Images/ACNH_VillagerIcons/Nibbles.png"},
        {src: "Images/ACNH_VillagerIcons/Norma.png"},
        {src: "Images/ACNH_VillagerIcons/Octavian.png"},
        {src: "Images/ACNH_VillagerIcons/OHare.png"},
        {src: "Images/ACNH_VillagerIcons/Olaf.png"},
        {src: "Images/ACNH_VillagerIcons/Olive.png"},
        {src: "Images/ACNH_VillagerIcons/Olivia.png"},
        {src: "Images/ACNH_VillagerIcons/Opal.png"},
        {src: "Images/ACNH_VillagerIcons/Ozzie.png"},
        {src: "Images/ACNH_VillagerIcons/Pancetti.png"},
        {src: "Images/ACNH_VillagerIcons/Pango.png"},
        {src: "Images/ACNH_VillagerIcons/Paolo.png"},
        {src: "Images/ACNH_VillagerIcons/Papi.png"},
        {src: "Images/ACNH_VillagerIcons/Pashmina.png"},
        {src: "Images/ACNH_VillagerIcons/Pate.png"},
        {src: "Images/ACNH_VillagerIcons/Patty.png"},
        {src: "Images/ACNH_VillagerIcons/Paula.png"},
        {src: "Images/ACNH_VillagerIcons/Peaches.png"},
        {src: "Images/ACNH_VillagerIcons/Peanut.png"},
        {src: "Images/ACNH_VillagerIcons/Pecan.png"},
        {src: "Images/ACNH_VillagerIcons/Peck.png"},
        {src: "Images/ACNH_VillagerIcons/Peewee.png"},
        {src: "Images/ACNH_VillagerIcons/Peggy.png"},
        {src: "Images/ACNH_VillagerIcons/Pekoe.png"},
        {src: "Images/ACNH_VillagerIcons/Penelope.png"},
        {src: "Images/ACNH_VillagerIcons/Phil.png"},
        {src: "Images/ACNH_VillagerIcons/Phoebe.png"},
        {src: "Images/ACNH_VillagerIcons/Pierce.png"},
        {src: "Images/ACNH_VillagerIcons/Pietro.png"},
        {src: "Images/ACNH_VillagerIcons/Pinky.png"},
        {src: "Images/ACNH_VillagerIcons/Piper.png"},
        {src: "Images/ACNH_VillagerIcons/Pippy.png"},
        {src: "Images/ACNH_VillagerIcons/Plucky.png"},
        {src: "Images/ACNH_VillagerIcons/Pompom.png"},
        {src: "Images/ACNH_VillagerIcons/Poncho.png"},
        {src: "Images/ACNH_VillagerIcons/Poppy.png"},
        {src: "Images/ACNH_VillagerIcons/Portia.png"},
        {src: "Images/ACNH_VillagerIcons/Prince.png"},
        {src: "Images/ACNH_VillagerIcons/Puck.png"},
        {src: "Images/ACNH_VillagerIcons/Puddles.png"},
        {src: "Images/ACNH_VillagerIcons/Pudge.png"},
        {src: "Images/ACNH_VillagerIcons/Punchy.png"},
        {src: "Images/ACNH_VillagerIcons/Purrl.png"},
        {src: "Images/ACNH_VillagerIcons/Queenie.png"},
        {src: "Images/ACNH_VillagerIcons/Quillson.png"},
        {src: "Images/ACNH_VillagerIcons/Raddle.png"},
        {src: "Images/ACNH_VillagerIcons/Rasher.png"},
        {src: "Images/ACNH_VillagerIcons/Raymond.png"},
        {src: "Images/ACNH_VillagerIcons/Renee.png"},
        {src: "Images/ACNH_VillagerIcons/Reneigh.png"},
        {src: "Images/ACNH_VillagerIcons/Rex.png"},
        {src: "Images/ACNH_VillagerIcons/Rhonda.png"},
        {src: "Images/ACNH_VillagerIcons/Ribbot.png"},
        {src: "Images/ACNH_VillagerIcons/Ricky.png"},
        {src: "Images/ACNH_VillagerIcons/Rizzo.png"},
        {src: "Images/ACNH_VillagerIcons/Roald.png"},
        {src: "Images/ACNH_VillagerIcons/Robin.png"},
        {src: "Images/ACNH_VillagerIcons/Rocco.png"},
        {src: "Images/ACNH_VillagerIcons/Rocket.png"},
        {src: "Images/ACNH_VillagerIcons/Rod.png"},
        {src: "Images/ACNH_VillagerIcons/Rodeo.png"},
        {src: "Images/ACNH_VillagerIcons/Rodney.png"},
        {src: "Images/ACNH_VillagerIcons/Rolf.png"},
        {src: "Images/ACNH_VillagerIcons/Rooney.png"},
        {src: "Images/ACNH_VillagerIcons/Rory.png"},
        {src: "Images/ACNH_VillagerIcons/Roscoe.png"},
        {src: "Images/ACNH_VillagerIcons/Rosie.png"},
        {src: "Images/ACNH_VillagerIcons/Rowan.png"},
        {src: "Images/ACNH_VillagerIcons/Ruby.png"},
        {src: "Images/ACNH_VillagerIcons/Rudy.png"},
        {src: "Images/ACNH_VillagerIcons/Sally.png"},
        {src: "Images/ACNH_VillagerIcons/Samson.png"},
        {src: "Images/ACNH_VillagerIcons/Sandy.png"},
        {src: "Images/ACNH_VillagerIcons/Savannah.png"},
        {src: "Images/ACNH_VillagerIcons/Scoot.png"},
        {src: "Images/ACNH_VillagerIcons/Shari.png"},
        {src: "Images/ACNH_VillagerIcons/Sheldon.png"},
        {src: "Images/ACNH_VillagerIcons/Shep.png"},
        {src: "Images/ACNH_VillagerIcons/Sherb.png"},
        {src: "Images/ACNH_VillagerIcons/Simon.png"},
        {src: "Images/ACNH_VillagerIcons/Skye.png"},
        {src: "Images/ACNH_VillagerIcons/Sly.png"},
        {src: "Images/ACNH_VillagerIcons/Snake.png"},
        {src: "Images/ACNH_VillagerIcons/Snooty.png"},
        {src: "Images/ACNH_VillagerIcons/Soleil.png"},
        {src: "Images/ACNH_VillagerIcons/Sparro.png"},
        {src: "Images/ACNH_VillagerIcons/Spike.png"},
        {src: "Images/ACNH_VillagerIcons/Spork.png"},
        {src: "Images/ACNH_VillagerIcons/Sprinkle.png"},
        {src: "Images/ACNH_VillagerIcons/Sprocket.png"},
        {src: "Images/ACNH_VillagerIcons/Static.png"},
        {src: "Images/ACNH_VillagerIcons/Stella.png"},
        {src: "Images/ACNH_VillagerIcons/Sterling.png"},
        {src: "Images/ACNH_VillagerIcons/Stinky.png"},
        {src: "Images/ACNH_VillagerIcons/Stitches.png"},
        {src: "Images/ACNH_VillagerIcons/Stu.png"},
        {src: "Images/ACNH_VillagerIcons/Sydney.png"},
        {src: "Images/ACNH_VillagerIcons/Sylvana.png"},
        {src: "Images/ACNH_VillagerIcons/Sylvia.png"},
        {src: "Images/ACNH_VillagerIcons/Tabby.png"},
        {src: "Images/ACNH_VillagerIcons/Tad.png"},
        {src: "Images/ACNH_VillagerIcons/Tammi.png"},
        {src: "Images/ACNH_VillagerIcons/Tammy.png"},
        {src: "Images/ACNH_VillagerIcons/Tangy.png"},
        {src: "Images/ACNH_VillagerIcons/Tank.png"},
        {src: "Images/ACNH_VillagerIcons/Tasha.png"},
        {src: "Images/ACNH_VillagerIcons/TBone.png"},
        {src: "Images/ACNH_VillagerIcons/Teddy.png"},
        {src: "Images/ACNH_VillagerIcons/Tex.png"},
        {src: "Images/ACNH_VillagerIcons/Tia.png"},
        {src: "Images/ACNH_VillagerIcons/Tiffany.png"},
        {src: "Images/ACNH_VillagerIcons/Timbra.png"},
        {src: "Images/ACNH_VillagerIcons/Tipper.png"},
        {src: "Images/ACNH_VillagerIcons/Tom.png"},
        {src: "Images/ACNH_VillagerIcons/Truffles.png"},
        {src: "Images/ACNH_VillagerIcons/Tucker.png"},
        {src: "Images/ACNH_VillagerIcons/Tutu.png"},
        {src: "Images/ACNH_VillagerIcons/Twiggy.png"},
        {src: "Images/ACNH_VillagerIcons/Tybalt.png"},
        {src: "Images/ACNH_VillagerIcons/Ursala.png"},
        {src: "Images/ACNH_VillagerIcons/Velma.png"},
        {src: "Images/ACNH_VillagerIcons/Vesta.png"},
        {src: "Images/ACNH_VillagerIcons/Vic.png"},
        {src: "Images/ACNH_VillagerIcons/Victoria.png"},
        {src: "Images/ACNH_VillagerIcons/Violet.png"},
        {src: "Images/ACNH_VillagerIcons/Vivian.png"},
        {src: "Images/ACNH_VillagerIcons/Vladimir.png"},
        {src: "Images/ACNH_VillagerIcons/Wade.png"},
        {src: "Images/ACNH_VillagerIcons/Walker.png"},
        {src: "Images/ACNH_VillagerIcons/Walt.png"},
        {src: "Images/ACNH_VillagerIcons/Wart_Jr.png"},
        {src: "Images/ACNH_VillagerIcons/Weber.png"},
        {src: "Images/ACNH_VillagerIcons/Wendy.png"},
        {src: "Images/ACNH_VillagerIcons/Whitney.png"},
        {src: "Images/ACNH_VillagerIcons/Willow.png"},
        {src: "Images/ACNH_VillagerIcons/Winnie.png"},
        {src: "Images/ACNH_VillagerIcons/Wolfgang.png"},
        {src: "Images/ACNH_VillagerIcons/Yuka.png"},
        {src: "Images/ACNH_VillagerIcons/Zell.png"},
        {src: "Images/ACNH_VillagerIcons/Zucker.png"}
    ];

    var arrayLength = imageArray.length;  
    var newArray = [];  

    for (var i = 0; i < arrayLength; i++)   
       {  
            newArray[i] = new Image();  
            newArray[i].src = imageArray[i].src; 
        }; 

    function getRandomNum()   
    {  do {
        // generate and return a random number for the image to be displayed   
        imgNo = Math.floor(Math.random() * arrayLength);  
        return newArray[imgNo];  
        } while (newArray.indexOf(imgNo) !== -1);
    };
    
    var newImage = getRandomNum(0, newArray.length - 1);
    

    // display the new random image   
    if (spaceID != 12) {
        document.getElementById(spaceID).append(newImage);
    };

  
};

  
  